---
Name: verifiable-config
---

SilverStripe\Core\Injector\Injector:
  BackendService:
    factory: PhpTek\Verifiable\Backend\BackendServiceFactory

PhpTek\Verifiable\Model\VerifiableExtension:
  dependencies:
    service: '%$BackendService'
    
PhpTek\Verifiable\Controller\VerifiableController:
  dependencies:
    service: '%$BackendService'
    
PhpTek\Verifiable\Controller\UpdateProofController:
  dependencies:
    service: '%$BackendService'